# deployment를 사용해서 백엔드 생성
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cdm-ui-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cdm-ui-backend
            tier: backend
    template:
        metadata:
            labels:
                app: cdm-ui-backend
                tier: backend
        spec:
            containers:
                - name: cdm-ui-backend
                  image: registry.datacommand.co.kr/cdm-ui-backend:develop
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8443
                  env:
                      - name: NODE_ENV
                        value: production

            restartPolicy: Always
---
# cdm-ui-backend 서비스 오브젝트 생성
# 서비스는 트래픽을 보내는 파드를 찾기 위해 셀렉터를 사용한다
apiVersion: v1
kind: Service
metadata:
    name: cdm-ui-backend
spec:
    ports:
        - port: 8443
    selector:
        app: cdm-ui-backend
        tier: backend
