# deployment를 사용해서 백엔드 생성
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdm-ui-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdm-ui-backend
      tier: backend
  template:
    metadata:
      labels:
        app: cdm-ui-backend
        tier: backend
    spec:
      serviceAccount: datacommand
      containers:
        - name: cdm-ui-backend
          image: datacommand2/cdm-ui-backend:shinhansec-PoC-v1.1.0-pre.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          env:
            - name: NODE_ENV
              value: production
#            - name: HOST_IP
#              value: 192.168.1.90
              
          volumeMounts:
            - name: event-code-message
              mountPath: "/app/src/event-code/cdm_event_code_message.json"
            - name: event-error
              mountPath: "/app/src/event-code/cdm_event_error.json"
            - name: event-code
              mountPath: "/app/src/event-code/cdm_event_code.json"
      
      volumes:
        - name: event-code-message
          hostPath:
            path: "/mnt/event-code/cdm_event_code_message.json"
        - name: event-error
          hostPath:
            path: "/mnt/event-code/cdm_event_error.json"
        - name: event-code
          hostPath:
            path: "/mnt/event-code/cdm_event_code.json"
            
      restartPolicy: Always
---
# cdm-ui-backend 서비스 오브젝트 생성
# 서비스는 트래픽을 보내는 파드를 찾기 위해 셀렉터를 사용한다
apiVersion: v1
kind: Service
metadata:
  name: cdm-ui-backend
spec:
  ports:
    - port: 8443
  selector:
    app: cdm-ui-backend
    tier: backend
