/**
 *
 * CDM-DisasterRecovery
 *
 *
 * 설명추가
 *
 * Version: v1
 *
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

import { requestApi } from '../../../utils/api';

// package openapi3graphql-server

// migration_job_api

export default {
    Query: {
        // 마이그레이션 작업 상태 조회
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @return [OpenStackDrMessageResponse]
        GetMigrationJobStatus: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.groupId}/migration_plans/${args.planId}/migration`,
                method: 'GET',
                params: {
                    group_id: args.groupId,
                    plan_id: args.planId,
                },
            });

            return {
                job_type: result?.data?.job_type,
                status: result?.data?.status,
            };
        },
    },

    Mutation: {
        // 마이그레이션 작업 등록
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @param String jobType 마이그레이션 타입(\&quot;simulation\&quot; 또는 \&quot;cutover\&quot;)
        // @return [OpenStackDrMessageResponse]
        CreateMigrationJob: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.input.groupId}/migration_plans/${args.input.planId}/migration`,
                method: 'POST',
                params: {
                    group_id: args.input.groupId,
                    plan_id: args.input.planId,
                    job_type: args.input.jobType,
                },
            });

            return {
                message: result?.data?.message,
            };
        },
    },
};
