/**
 *
 * CDM-DisasterRecovery
 *
 *
 * 설명추가
 *
 * Version: v1
 *
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

import { requestApi } from '../../../utils/api';

// package openapi3graphql-server

// migration_replication_api

export default {
    Query: {
        // 마이그레이션 복제 상태 조회
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @return [OpenStackDrMigrationReplicationStatusResponse]
        GetMigrationReplicationStatus: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.groupId}/migration_plans/${args.planId}/replication`,
                method: 'GET',
                params: {
                    group_id: args.groupId,
                    plan_id: args.planId,
                },
            });

            return {
                status: result?.data?.status,
            };
        },
    },

    Mutation: {
        // 마이그레이션 복제 싱크(데이터 동기화)
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @param Boolean replicator replicator 옵션
        // @return [OpenStackDrMessageResponse]
        CreateMigrationPreparation: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.input.groupId}/migration_plans/${args.input.planId}/replication`,
                method: 'POST',
                params: {
                    group_id: args.input.groupId,
                    plan_id: args.input.planId,
                    replicator: args.input.replicator,
                },
            });

            return {
                message: result?.data?.message,
            };
        },

        // 마이그레이션 복제 시작
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @param Boolean replicator replicator 옵션
        // @return [OpenStackDrMessageResponse]
        CreateMigrationReplication: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.input.groupId}/migration_plans/${args.input.planId}/replication`,
                method: 'POST',
                params: {
                    group_id: args.input.groupId,
                    plan_id: args.input.planId,
                    replicator: args.input.replicator,
                },
            });

            return {
                message: result?.data?.message,
            };
        },

        // 마이그레이션 복제 삭제
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @return [OpenStackDrMessageResponse]
        DeleteMigrationReplication: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.input.groupId}/migration_plans/${args.input.planId}/replication`,
                method: 'DELETE',
                params: {
                    group_id: args.input.groupId,
                    plan_id: args.input.planId,
                },
            });

            return {
                message: result?.data?.message,
            };
        },
    },
};
