/**
 *
 * CDM-DisasterRecovery
 *
 *
 * 설명추가
 *
 * Version: v1
 *
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

import { requestApi } from '../../../utils/api';

// package openapi3graphql-server

// migration_plan_api

export default {
    Query: {
        // 마이그레이션 계획 상세 조회
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @return [OpenStackDrMigrationResponse]
        GetMigration: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.groupId}/migration_plans/${args.planId}`,
                method: 'GET',
                params: {
                    group_id: args.groupId,
                    plan_id: args.planId,
                },
            });

            return {
                plan: result?.data?.plan,
            };
        },

        // 마이그레이션 계획 목록 조회
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int limit 한 페이지에 표시할 항목 개수
        // @param Int offset 페이지에 표시할 항목 인덱스
        // @param Int ownerGroupId 보호그룹 원본 클러스터의 Owner 그룹 ID
        // @param String name 마이그레이션 계획 이름
        // @return [OpenStackDrMigrationsResponse]
        GetMigrations: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.groupId}/migration_plans`,
                method: 'GET',
                params: {
                    name: args.name,
                    group_id: args.groupId,
                    limit: args.limit,
                    offset: args.offset,
                    owner_group_id: args.ownerGroupId,
                },
            });

            return {
                plans: result?.data?.plans ?? [],
                pagination: result?.data?.pagination,
            };
        },
    },

    Mutation: {
        // 마이그레이션 계획 삭제
        // 설명추가
        // @param Int groupId 보호그룹 ID
        // @param Int planId 마이그레이션 계획 ID
        // @return [OpenStackDrMessageResponse]
        DeleteMigration: async (_: any, args: any, context: any) => {
            const result = await requestApi({
                context,
                originalUrl: `/recovery/groups/${args.input.groupId}/migration_plans/${args.input.planId}`,
                method: 'DELETE',
                params: {
                    group_id: args.input.groupId,
                    plan_id: args.input.planId,
                },
            });

            return {
                message: result?.data?.message,
            };
        },
    },
};
